# Macro file for the visualization setting in the initialization phase 
# of the B1 example when running in interactive mode
#

# Use these open statements to open selected visualization
#
# Use this open statement to create an OpenGL view:
/vis/open OGLIQt 600x600-0+0
#
# Use this open statement to create an OpenInventor view:
#/vis/open OI
#
# Use this open statement to create a .prim file suitable for
# viewing in DAWN:
#/vis/open DAWNFILE
#
# Use this open statement to create a .heprep file suitable for
# viewing in HepRApp:
#/vis/open HepRepFile
#
# Use this open statement to create a .wrl file suitable for
# viewing in a VRML viewer:
#/vis/open VRML2FILE
#
#/vis/open RayTracerX
# Use this open statement to create an offscreen file with TSG:
#/vis/open TSG_OFFSCREEN 1200x1200
# See the tsg_offscreen.mac file for more commands to change
# the file format, file name, picture size, etc.
#
# Disable auto refresh and quieten vis messages whilst scene and
# trajectories are established:
/vis/viewer/set/autoRefresh false
/vis/verbose errors
#
# Draw geometry:
/vis/drawVolume
#
# Specify view angle:
/vis/viewer/set/viewpointVector -1 0 0
/vis/viewer/set/lightsVector -1 0 0
#
# Specify style (surface, wireframe, auxiliary edges,...)
/vis/viewer/set/style wireframe
/vis/viewer/set/auxiliaryEdge true
/vis/viewer/set/lineSegmentsPerCircle 20
#
# Draw smooth trajectories at end of event, showing trajectory points
# as markers 2 pixels wide:
/vis/scene/add/trajectories smooth
/vis/modeling/trajectories/create/drawByCharge
/vis/modeling/trajectories/drawByCharge-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByCharge-0/default/setStepPtsSize 2
# (if too many tracks cause core dump => /tracking/storeTrajectory 0)
#
# Draw hits at end of event:
#/vis/scene/add/hits
#
# To draw only gammas:
#/vis/filtering/trajectories/create/particleFilter
#/vis/filtering/trajectories/particleFilter-0/add gamma
#
# To invert the above, drawing all particles except gammas,
# keep the above two lines but also add:
#/vis/filtering/trajectories/particleFilter-0/invert true
#
# Many other options are available with /vis/modeling and /vis/filtering.
# For example, to select colour by particle ID:
#/vis/modeling/trajectories/create/drawByParticleID
#/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
# To select or override default colours (note: e+ is blue by default):
#/vis/modeling/trajectories/list
#/vis/modeling/trajectories/drawByParticleID-0/set e+ yellow
#
# To superimpose all of the events from a given run:
#/vis/scene/endOfEventAction accumulate
#
# Decorations
# Name
#/vis/set/textColour green
#/vis/set/textLayout right
#/vis/scene/add/text2D 0.9 -.9 24 ! ! exampleB1
# or, if your system does not support right-adjustment
#/vis/scene/add/text2D 0 -.9 24 ! ! exampleB1
#/vis/set/textLayout    # Revert to normal (left adjusted) layout
#/vis/set/textColour    # Revert to default text colour (blue)
#
# Axes, scale, etc.
#/vis/scene/add/scale   # Simple scale line
/vis/scene/add/axes  -0  -0  -0 20 cm  # Simple axes: x=red, y=green, z=blue
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
#
# Frame
/vis/set/colour red
/vis/set/lineWidth 2
/vis/scene/add/frame   # Simple frame around the view
/vis/set/colour        # Revert to default colour (white)
/vis/set/lineWidth     # Revert to default line width (1.)
#
# Attach text to one edge of Shape1, with a small, fixed offset
#/vis/scene/add/text 0 6 -4 cm 18 4 4 Shape1
# Attach text to one corner of Shape2, with a small, fixed offset
#/vis/scene/add/text 6 7 10 cm 18 4 4 Shape2
#
# To get nice view
# Make the "World" box invisible
/vis/geometry/set/visibility World 0 false
#/vis/geometry/set/visibility LM0disc 0 false
# "Envelope" is transparent blue to represent water
#/vis/geometry/set/colour Envelope 0 0 0 1 .3

# frontplate
/vis/geometry/set/colour LSpiralDrain 0 0 0 4.
/vis/geometry/set/colour LM0disc 0 2.7 1.54 0
/vis/geometry/set/colour LLitiumdisc 0 0.5 3.74 0


# backplate
/vis/geometry/set/colour BackPlateGroove_Log 0 0 0 1 .3
/vis/geometry/set/colour PitBase_Log 0 0 0 1 .3
/vis/geometry/set/colour PitMiddleDisk_Log 0 0 0 1 .3
/vis/geometry/set/colour PitCap_Log 0 0 0 1 .3


# Neutron Moderator
/vis/geometry/set/colour ModeratorGlassDisk_Log 0.2 0.2 0.2 1 1

# CoolingPipese
/vis/geometry/set/colour PipeShell_Log 0 0 2 0.5 .6
/vis/geometry/set/colour WaterInPipe_Log 0 0 0 1 .5
/vis/geometry/set/colour FittingPipe 1 1 1 1

# Phantom
#/vis/geometry/set/colour template_BrainCell_Log 0 0 0.8 1. .9
/vis/geometry/set/colour template_BrainCell_Log 0 0.603 0.200 0.450
/vis/geometry/set/colour template_BoneCell_Log 0 0.8 0.9 0.8
/vis/geometry/set/colour template_SkinCell_Log 0 1. 0.8 0.

# Cells Phantom
/vis/geometry/set/colour PhantomDisk_Log 1 1 1 1 .5

#MiceWood
/vis/geometry/set/colour MiceDisk_Log 0 0 2 0.5 .6
/vis/geometry/set/colour WoodDisk_Log 1 1 1 1


/vis/viewer/set/style surface
/vis/viewer/set/hiddenMarker true
/vis/viewer/set/viewpointThetaPhi 120 150
#
# Re-establish auto refreshing and verbosity:
/vis/viewer/set/autoRefresh true
/vis/verbose warnings
#
# For file-based drivers, use this to create an empty detector view:
#/vis/viewer/flush
